INSERT INTO students (city, company, email, first_name, last_name, pic, skill)
    VALUES
    ('Fushë-Muhurr', 'Yadel', 'iorton0@imdb.com', 'Ingaberg', 'Orton', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/voluptasdictablanditiis.jpg', 'Oracle'), 
	('Sanghan', 'Avamm', 'cboards1@weibo.com', 'Clarke', 'Boards', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/voluptasautreprehenderit.jpg', 'Sports'), 
	('Kugesi', 'Skalith', 'lromanet2@wired.com', 'Laurens', 'Romanet', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/aspernaturnonsapiente.jpg', 'Employee Handbooks'), 
	('Krajan', 'Mybuzz', 'bskitt3@aboutads.info', 'Berti', 'Skitt', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/autautdeserunt.jpg', 'Nutrition Education'), 
	('Huiqi', 'Avavee', 'msummerley4@craigslist.org', 'Mureil', 'Summerley', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/consequaturdelectusquis.jpg', 'ISO 14971'), 
	('Jianghong', 'Twinte', 'rcoryndon5@cargocollective.com', 'Robbyn', 'Coryndon', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/autautdeserunt.jpg', 'Cinema 4D'), 
	('Sanxi', 'Buzzster', 'seykel6@examiner.com', 'Sheena', 'Eykel', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/utquamut.jpg', 'Ulead VideoStudio'), 
	('Huancheng', 'Edgeblab', 'mewen7@ycombinator.com', 'Minnnie', 'Ewen', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/nesciuntrerumlibero.jpg', 'Vulcan'), 
	('Luoxiong', 'Fadeo', 'riban8@hubpages.com', 'Rory', 'Iban', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/autemporroplaceat.jpg', 'EE4'), 
	('Toulon', 'Yakidoo', 'lroxby9@cam.ac.uk', 'Lenna', 'Roxby', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/doloribusquitempora.jpg', 'LPS'), 
	('Lazo', 'Photolist', 'rfitzalana@parallels.com', 'Rosalynd', 'FitzAlan', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/utquamut.jpg', 'Geography'), 
	('Bichura', 'Babblestorm', 'srapellib@adobe.com', 'Stephanie', 'Rapelli', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/enimpariaturoptio.jpg', 'Identity Management'), 
	('Chvalšiny', 'Mynte', 'mmacdirmidc@plala.or.jp', 'Maire', 'MacDirmid', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/aspernaturnonsapiente.jpg', 'Outdoor Advertising'), 
	('Itaparica', 'Photospace', 'nshepherdd@desdev.cn', 'Nicoline', 'Shepherd', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/nonipsaet.jpg', 'Amazon VPC'), 
	('Praia da Vitória', 'Vitz', 'ythornse@github.com', 'Yoshi', 'Thorns', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/voluptasdictablanditiis.jpg', 'DMR'), 
	('Sambir', 'Twitterwire', 'mtothef@shutterfly.com', 'Marna', 'Tothe', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/utquamut.jpg', 'PFI'), 
	('Sarulla', 'Blogpad', 'okearyg@g.co', 'Orelia', 'Keary', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/enimpariaturoptio.jpg', 'General Surgery'), 
	('Ochakovo-Matveyevskoye', 'Mydeo', 'mswaith@cafepress.com', 'Moses', 'Swait', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/velitnonquibusdam.jpg', 'Sales Tax'), 
	('Youxi Chengguanzhen', 'Avaveo', 'fnusseyi@skyrock.com', 'Fonsie', 'Nussey', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/remtemporavelit.jpg', 'Urbanism'), 
	('Limoges', 'Tazzy', 'srydingsj@phoca.cz', 'Skelly', 'Rydings', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/etporroalias.jpg', 'IFTA'), 
	('Łobżenica', 'Quatz', 'obrennekek@yellowbook.com', 'Olly', 'Brenneke', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/velitnonquibusdam.jpg', 'ATM Networks'), 
	('Divo', 'Gigazoom', 'nbadwickl@nifty.com', 'Norby', 'Badwick', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/delenitiestdolorum.jpg', 'Media Relations'), 
	('Sortavala', 'Eamia', 'mmichiem@nifty.com', 'Melody', 'Michie', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/sitlaborecorrupti.jpg', 'PC Games'), 
	('Taupo', 'Midel', 'jwillougheyn@psu.edu', 'Janice', 'Willoughey', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/dolordoloremassumenda.jpg', 'Kondor+'), 
	('Krajandadapmulyo', 'Wikibox', 'ggallymoreo@mashable.com', 'Geraldine', 'Gallymore', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/sitlaborecorrupti.jpg', 'WTL');